// FAKE DATA
export const shoes = [
  {
    id: 1,
    title: "Wild Rider Layers Unisex Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/380697/02/sv01/fnd/IND/fmt/png/,Wild-Rider-Layers-Unisex-Sneakers",
    originalPrice: 69.99,
    salePrice: 59.99,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Wild Rider Layers 2 Unisex Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/380697/03/sv01/fnd/IND/fmt/png/Wild-Rider-Layers-Unisex-Sneakers",
    originalPrice: 120.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Wild Rider Layers Unisex3 sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/380697/01/sv01/fnd/IND/fmt/png/Wild-Rider-Layers-Unisex-Sneakers",
    originalPrice: 45.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "PUMA Serve Pro Lite Unisex shoes",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/374902/11/sv01/fnd/IND/fmt/png/PUMA-Serve-Pro-Lite-Unisex-Shoes",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "PUMA Serve Pro Lite Unisex",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/375314/01/sv01/fnd/IND/fmt/png/one8-Virat-Kohli-Basket-Classic-Unisex-Sneakers",
    originalPrice: 110.75,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "one8 Virat Kohli Basket Classice Unisex Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/369863/18/sv01/fnd/IND/fmt/png/Caracal-SoftFoam+-Sneakers",
    originalPrice: 66.98,
    salePrice: 56.98,
    rating: 5,
  },
  {
    id: 7,
    title: "Caracal SoftFoam+Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/375168/01/sv01/fnd/IND/fmt/png/Mirage-Mox-Brightly-Packed-Shoes",
    originalPrice: 39.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 8,
    title: "Mirage Mox Brightly Packed Shoes",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/371149/69/sv01/fnd/IND/fmt/png/Future-Rider-Play-On-Unisex-Sneakers",
    originalPrice: 58.79,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Future Rider Play On Unisex Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/371149/68/sv01/fnd/IND/fmt/png/Future-Rider-Play-On-Unisex-Sneakers",
    originalPrice: 99.99,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Future Rider2 Play On Unisex Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/371149/72/sv01/fnd/IND/fmt/png/Future-Rider-Play-On-Unisex-Sneakers",
    originalPrice: 120.29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "Future Rider3 Play On Unisex Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/370914/01/sv01/fnd/IND/fmt/png/Rebound-Lay-Up-Lo-SoftFoam+-Mesh-Shoes",
    originalPrice: 89.99,
    salePrice: null,
    rating: 5,
  },
  {
    id: 12,
    title: "Rebound Lay-Up Lo SoftFoam+Mesh Shoes",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1500,h_1500/global/375314/02/sv01/fnd/IND/fmt/png/one8-Virat-Kohli-Basket-Classic-Unisex-Sneakers",
    originalPrice: 36.78,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 13,
    title: "one8 Virat Kohli Basket Classic Unisex Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/375168/01/sv01/fnd/IND/fmt/png/Mirage-Mox-Brightly-Packed-Shoes",
    originalPrice: 36.78,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 14,
    title: "Mirage Mox Brightly Packed Shoes",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/375168/01/sv01/fnd/IND/fmt/png/Mirage-Mox-Brightly-Packed-Shoes",
    originalPrice: 36.78,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 15,
    title: "PUMA Backcourt IMEVA Mid Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1050,h_1050/global/374139/01/sv01/fnd/IND/fmt/png/PUMA-Backcourt-IMEVA-Mid-Sneakers",
    originalPrice: 36.78,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 16,
    title: "Redon Move Shoes",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1050,h_1050/global/185999/02/sv01/fnd/IND/fmt/png/Redon-Move--Shoes",
    originalPrice: 36.78,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 17,
    title: "Puma Perforated Low Men's IDP Shoes",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1050,h_1050/global/372981/01/sv01/fnd/IND/fmt/png/Puma-Perforated-Low-Men's--IDP-Shoes",
    originalPrice: 36.78,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 18,
    title: "RS-2K Internet Exploring Sneakers",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1050,h_1050/global/373309/21/sv01/fnd/IND/fmt/png/RS-2K-Internet-Exploring-Sneakers",
    originalPrice: 36.78,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 19,
    title: "Rebound Lay-Up Lo SoftFoam+Mesh Shoes",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1050,h_1050/global/373108/13/sv01/fnd/IND/fmt/png/X-Ray-2-Square-IMEVA-SoftFoam+-Shoes",
    originalPrice: 36.78,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 20,
    title: "Future Rider International Game Shoes",
    url: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1050,h_1050/global/375971/01/sv01/fnd/IND/fmt/png/Future-Rider-International-Game-Shoes",
    originalPrice: 36.78,
    salePrice: null,
    rating: 4.5,
  },
];